# Generated by Django 4.1.3 on 2022-11-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='images')),
                ('category', models.CharField(choices=[('Crutches', 'Crutches'), ('Walker', 'Walker'), ('Scooter', 'Scooter'), ('Wheelchair', 'Wheelchair'), ('Hospital bed', 'Hospital bed'), ('CPAP Machine', 'CPAP Machine'), ('Toiletting', 'Toiletting'), ('Baby supplies', 'Baby supplies'), ('Recliners', 'Recliners')], max_length=100)),
                ('buy_price', models.FloatField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rent_price', models.FloatField()),
                ('rent_duration', models.IntegerField()),
            ],
        ),
    ]
