# Generated by Django 4.1.3 on 2022-11-12 19:02

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=posts.models.postImageFile, verbose_name='images'),
        ),
    ]
